#!/bin/bash

# Script to help download icons from Figma
# This script provides instructions and can be extended to automate downloads

echo "=========================================="
echo "Figma Icon Download Helper"
echo "=========================================="
echo ""
echo "This script helps you download icons from Figma."
echo ""
echo "Figma File: https://www.figma.com/design/uHeMORx8NZy2oehud5auFn/Fluen-AI---AI-Language-Learning-App-Ui-Kit?node-id=5003-1416"
echo ""
echo "To download icons:"
echo "1. Open the Figma file in your browser"
echo "2. Select the icon you want to export"
echo "3. In the right panel, click 'Export'"
echo "4. Choose SVG format (preferred) or PNG"
echo "5. Save to: assets/icons/svg/ (for SVG) or assets/icons/png/ (for PNG)"
echo "6. Use kebab-case naming (e.g., left_arrow.svg, home_04.svg)"
echo ""
echo "After adding icons, run:"
echo "  fluttergen"
echo "  # OR"
echo "  flutter pub run build_runner build"
echo ""
echo "This will generate type-safe accessors in lib/gen/assets.gen.dart"
echo ""
echo "=========================================="
echo "Icon List (from Figma design):"
echo "=========================================="
echo ""
echo "Navigation: left_arrow, right_arrow, arrow_left_01_round, arrow_right_01_round, arrow_up_01_round, arrow_down_01_round, arrow_up_right_01_round"
echo "Common UI: more, cross, checkmark, checkmark_circle_02, checkmark_badge_02, plus_sign, plus_sign_circle, minus_sign, search, filter_horizontal, sorting_01, heart, star, star_circle, share, delete_03, repeat, download_01, download_circle_02, lock_keyhole_minimalistic, setting_02, crown, user, user_group, message_02, calendar_03, clock, target, statistics, gem, words, bulb, square, tick_02, happy, sign, other"
echo "Media: play, pause, speaker, mic_02, video_02, video_off, camera, camera_add_01, camera_plus, camera_01, image_02, rewind_10_seconds_forward, rewind_10_seconds_back"
echo "Content: book, book_open_01, book_bookmark_02, note, pen, pen_connect_bluetooth, sent, pdf_file, png, cc_square"
echo "Feature: home_04, analytics_01, ai, game, teaching, voice, mortarboard_02, work_bag, muscle, job, work, burger"
echo "Interaction: thumbs_up, thumbs_down, rejoin, zoom_out, credit_card, credit_card_add"
echo "Payment: mastercard, apple_pay"
echo "Flags: flag_02, usa, uk, australia, japan, china, bangladesh, canada, south_africa"
echo "Theme: sun, night"
echo ""

